name: Build Workflow
on: 
  push: #    branches: master
jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
          pip install pyinstaller
      
      - name: Run PyInstaller
        run: |
          python -m PyInstaller WebScrap.py
          echo "Listing dist directory:"
          dir dist
      
      - name: Create ZIP Archive
        run: |
          cd dist
          Compress-Archive -Path WebScrap -DestinationPath WebScrap.zip
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows_CRMWebScrapper
          path: dist/WebScrap.zip
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: dist/WebScrap.zip
          body: |
            Release v${{ github.run_number }}
            
            Instructions:
            1. Download WebScrap.zip
            2. Extract all files
            3. Run WebScrap.exe from the extracted folder
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
