name: Build Workflow
on: 
  push: #    branches: master
jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      
      - name: Verify Tkinter
        run: |
          python -c "import tkinter; print('Tkinter is available')"
      
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
          pip install pyinstaller
      
      - name: Run PyInstaller and Debug
        run: |
          python -m PyInstaller --name CRMWebScrapper WebScrap.py
          echo "Listing current directory:"
          dir
          echo "Listing dist directory:"
          dir dist
          echo "Listing dist directory contents:"
          dir dist\*.*
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows_CRMWebScrapper
          path: |
            dist/
            dist/**/*
            dist/CRMWebScrapper*
      
      - name: Create Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: |
            dist/WebScrap/*
          body: |
            Test Release v${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
