name: Build Workflow
on:
  push:
#    branches: master
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated to v4

      - name: Install Python
        uses: actions/setup-python@v5  # Updated to v5
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install requirements
        run: |
          pip install -r requirement.txt

      - name: Run PyInstaller
        run: |
          python -m PyInstaller CRMWebScrapper.spec

      - name: Upload artifact  # Updated to v3
        uses: actions/upload-artifact@v3
        with:
          name: Windows_CRMWebScrapper
          path: dist/CRMWebScrapper.exe

      - name: Create Release  # Updated to use softprops/action-gh-release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/CRMWebScrapper.exe
          tag_name: ${{ github.event.head_commit.message }}
          name: ${{ github.event.head_commit.message }}
          body: |
            Test Release v1.0.0
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}