name: Build Workflow
on: 
  push: #    branches: master
jobs:
  build-windows:
    runs-on: windows-latest
    permissions: # Add permissions
      contents: write # Required for creating releases
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      
      - name: Verify Tkinter
        run: |
          python -c "import tkinter; print('Tkinter is available')"
      
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
      
      - name: Run PyInstaller
        run: |
          python -m PyInstaller --name CRMWebScrapper WebScrap.py
          # Debug: List contents of dist directory
          dir dist
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows_CRMWebScrapper
          path: ./dist/CRMWebScrapper.exe
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # Only run on tags
        with:
          files: ./dist/CRMWebScrapper.exe
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Test Release v${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}