name: Build EXE on Push

on:
  push:
    branches:
      - main  # You can specify branches where this should trigger, e.g., `main` or `*` for all branches

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # Add any additional dependencies your script requires

      - name: Build the EXE
        run: |
          pyinstaller --onefile WebScrap.py  

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-exe
          path: dist/CRMWebScrap.exe  # Ensure this path matches the output of your script's compiled EXE
