# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller WebScrap.py
    # Optionally verify that it works (provided that it does not need user interaction)
    - run: ./dist/CRM-Web-Scrapper/WebScrap.py
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
